### ISSUE TITLE
Data callouts in plot_ly are tilted

### ISSUE THREAD

**Issue by stoltzmaniac** [stoltzmaniac/Medicare#11]
The data callouts are angled now that colors have been added. I tried moving the legend around and a couple of other things but cannot fix it. I don't see an attribute which can directly affect it either. Need help on this.

**Comment by ginberg** [comment]
hi @stoltzmaniac do you mean the hover text? This still looks normal to me. Can you add a screenshot maybe? nice addition to add colors btw

**Comment by stoltzmaniac** [comment]
![image](https://cloud.githubusercontent.com/assets/23501850/26789434/8accd26c-49cd-11e7-9ff5-5ce3d563a3ae.png)

**Comment by stoltzmaniac** [comment]
This is also available at https://stoltzmaniac.shinyapps.io/medicare_data/ @ginberg

**Comment by ginberg** [comment]
@stoltzmaniac that's weird! never seen it before
I just published your code and it works correct, see https://ginberg.shinyapps.io/medic/

You have the same on your local machine? What is your R studio version and sessionInfo() ?

**Comment by stoltzmaniac** [comment]
I'm using Ubuntu 16.04
Version 1.0.136 – © 2009-2016 RStudio, Inc.
The default browser it opens in is Chrome (other than the RStudio browser)

R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] plotly_4.5.6    DT_0.2          leaflet_1.1.0   scales_0.4.1    dplyr_0.5.0     purrr_0.2.2     readr_1.1.0     tidyr_0.6.1     tibble_1.3.0   
[10] tidyverse_1.1.1 zipcode_1.0     ggmap_2.6.1     ggplot2_2.2.1   stringr_1.1.0   RSQLite_1.1-2   shiny_1.0.0    

loaded via a namespace (and not attached):
 [1] reshape2_1.4.2    haven_1.0.0       lattice_0.20-33   colorspace_1.3-2  viridisLite_0.1.3 htmltools_0.3.5   yaml_2.1.14       base64enc_0.1-3  
 [9] foreign_0.8-66    DBI_0.5-1         sp_1.2-4          modelr_0.1.0      readxl_1.0.0      jpeg_0.1-8        plyr_1.8.4        cellranger_1.1.0 
[17] munsell_0.4.3     gtable_0.2.0      rvest_0.3.2       htmlwidgets_0.8   RgoogleMaps_1.4.1 mapproj_1.2-4     psych_1.7.3.21    memoise_1.0.0    
[25] forcats_0.2.0     crosstalk_1.0.0   httpuv_1.3.3      parallel_3.2.3    broom_0.4.2       proto_1.0.0       Rcpp_0.12.10      geosphere_1.5-5  
[33] xtable_1.8-2      jsonlite_1.3      mime_0.5          mnormt_1.5-5      rjson_0.2.15      hms_0.3           png_0.1-7         digest_0.6.12    
[41] stringi_1.1.2     grid_3.2.3        tools_3.2.3       magrittr_1.5      maps_3.1.1        lazyeval_0.2.0    rsconnect_0.7     xml2_1.1.1       
[49] lubridate_1.6.0   assertthat_0.1    httr_1.2.1        R6_2.2.0          nlme_3.1-124     
>

**Comment by stoltzmaniac** [comment]
Yours does render properly in my browser on shinyapps.io - hmmmm maybe a package updated? It's not working on my Windows dual boot either.

**Comment by stoltzmaniac** [comment]
I just updated RStudio to 1.0143 and it still isn't working properly. Hmmmm....

**Comment by ginberg** [comment]
I have the same Rstudio version (1.0143) and also Ubuntu 16.04 but R version 3.4

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=nl_NL.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=nl_NL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=nl_NL.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=nl_NL.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RCurl_1.95-4.8 bitops_1.0-6   RSQLite_1.1-2 

loaded via a namespace (and not attached):
[1] compiler_3.4.0 rsconnect_0.8  DBI_0.6-1      tools_3.4.0    memoise_1.1.0  Rcpp_0.12.10   RJSONIO_1.3-0  digest_0.6.12

**Comment by stoltzmaniac** [comment]
Upon testing out the new versions there are still issues, I'll work on it later on.

**Comment by stoltzmaniac** [comment]
Unsure as to whether or not it'll be possible to get to the newest version of R after doing sudo apt-get install r-base it returns information showing I'm up to date (even though it's 3.2 and I had previously run sudo apt-get update):

Reading package lists... Done
Building dependency tree       
Reading state information... Done
r-base is already the newest version (3.2.3-4).
r-base-dev is already the newest version (3.2.3-4).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-66 linux-headers-4.4.0-66-generic linux-headers-4.4.0-72
  linux-headers-4.4.0-72-generic linux-image-4.4.0-66-generic
  linux-image-4.4.0-72-generic linux-image-extra-4.4.0-66-generic
  linux-image-extra-4.4.0-72-generic linux-signed-image-4.4.0-66-generic
  linux-signed-image-4.4.0-72-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by stoltzmaniac** [comment]
Everything is back up and running

**Comment by ginberg** [comment]
glad you got it working!
